# Generated by Django 5.0.7 on 2024-08-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='addrss',
            new_name='address',
        ),
    ]
