# Generated by Django 5.0.7 on 2024-08-17 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_data', models.CharField(max_length=100)),
                ('event_time', models.CharField(max_length=100)),
                ('event_venue', models.TextField()),
                ('event_picture', models.ImageField(upload_to='event_picture/')),
                ('event_price', models.PositiveIntegerField()),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
