# Generated by Django 5.0.7 on 2024-08-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_user_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_picture',
            field=models.ImageField(upload_to='event_picture/'),
        ),
    ]
