# Generated by Django 5.0.7 on 2024-08-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookevent',
            name='total_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
